routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'language'], function () {
    Auth::routes();
    Route::get('/', 'PhotosController@index')->name('home');
    Route::resource('photos', 'PhotosController');
    Route::resource('users', 'UsersController')->only(['show']);
    Route::resource('comments', 'CommentsController')->except(['index', 'show', 'create']);
});

Route::get('language/{local}', 'LanguageSwitcherController@switcher')->name('language.switcher')
    ->where('local', 'en|ru');

app/User.php
<?php

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
        'uses_two_factor_auth',
        'two_factor_secret_code',
        'two_factor_recovery_code',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
        'last_login'           => 'datetime',
        'uses_two_factor_auth' => 'boolean',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
        'id',
        'name',
        'email',
        'permissions',
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'last_login',
        'updated_at',
        'created_at',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;

class UsersController extends Controller
{
    /**
     * UsersController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->only(['show']);
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }
}

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

    <h2>@lang('Photos'):</h2>
    @can('view', $user)
        <a href="{{route('photos.create')}}">@lang('Create new photo')</a>
    @endcan

    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">@lang('Photo')</th>
            <th scope="col">@lang('Title')</th>
            <th scope="col" colspan="2">@lang('Actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($user->photos as $photo)
            <tr>
                @if($photo->picture == 'no_picture')
                    <td>
                        <a href="{{route('photos.show', ['photo' => $photo])}}">
                            <img src="{{asset('img/no_img.jpg')}}" alt="no_img" style="width: 100px; height: 100px">
                        </a>
                    </td>
                @else
                    <td>
                        <a href="{{route('photos.show', ['photo' => $photo])}}">
                            <img src="{{asset('storage/' . $photo->picture)}}" alt="{{$photo->picture}}" style="width: 100px; height: 100px">
                        </a>
                    </td>
                @endif
                <td>{{$photo->title}}</td>
                <td>
                    @can('update', $photo)
                        <a href="{{route('photos.edit', ['photo' => $photo])}}">@lang('Edit')</a>
                    @endcan
                </td>
                <td>
                    @can('delete', $photo)
                        <form method="post" action="{{route('photos.destroy', ['photo' => $photo])}}">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger btn-sm">@lang('Remove')</button>
                        </form>
                    @endcan
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection