routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'language'], function () {
    Auth::routes();
    Route::get('/', 'PhotosController@index')->name('home');
    Route::resource('photos', 'PhotosController');
    Route::resource('users', 'UsersController')->only(['show']);
    Route::resource('comments', 'CommentsController')->except(['index', 'show', 'create']);
});

Route::get('language/{local}', 'LanguageSwitcherController@switcher')->name('language.switcher')
    ->where('local', 'en|ru');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'title',
        'user_id',
        'picture'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhotoRequest;
use App\Photo;

class PhotosController extends Controller
{
    /**
     * PhotosController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $photos = Photo::paginate(12);
        return view('photos.index', compact('photos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('photos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PhotoRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PhotoRequest $request)
    {
        $photo = new Photo($request->all());
        $photo->user_id = $request->user()->id;
        $file = $request->file('picture');
        $photo['picture'] = $file->store('photos', 'public');
        $photo->save();
        return redirect(route('photos.index'))->with('status', 'You have success added photo');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $photo = Photo::findOrFail($id);
        $comments_count = $photo->comments->count();
        $average_score = number_format($photo->comments->avg('rating'), 1);
        return view('photos.show', compact('photo', 'comments_count', 'average_score'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $photo = Photo::findOrFail($id);
        return view('photos.edit', compact('photo'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param PhotoRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(PhotoRequest $request, $id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('update', $photo);
        $data = $request->all();
        $file = $request->file('picture');
        $data['picture'] = $file->store('photos', 'public');
        $photo->update($data);

        return redirect(route('photos.index'))->with('status', 'You have success edited photo');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('delete', $photo);
        $photo->delete();
        return redirect(route('photos.index'))->with('status', 'You have success removed photo');
    }
}

resources/views/photos/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>@lang('Create photo')</h1>

    <form method="post" action="{{route('photos.store')}}" class="w-50" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label for="title">@lang('Caption')</label>
            <input class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="picture">@lang('Photo')</label>
            <input type="file" class="form-control-file @error('picture') is-invalid @enderror" id="picture" name="picture">
            @error('picture')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">@lang('Create')</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('photos.index')}}">@lang('Back')</a>
    </div>

@endsection

resources/views/photos/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1>@lang('Edit photo')</h1>

    <form method="post" action="{{route('photos.update', ['photo' => $photo])}}" class="w-50" enctype="multipart/form-data">
        @csrf
        @method('put')

        <div class="form-group">
            <label for="title">@lang('Caption')</label>
            <input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{$photo->title}}">
            @error('title')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        @if($photo->picture == 'no_picture')
            <img src="{{asset('img/no_img.jpg')}}" alt="no_img" style="width:100px;height:100px;">
        @else
            <img src="{{asset('storage/' . $photo->picture)}}" alt="{{$photo->picture}}" style="width:100px;height:100px;"><br/><br>
        @endif

        <div class="form-group">
            <label for="picture">@lang('Photo')</label>
            <input type="file" class="form-control-file @error('picture') is-invalid @enderror" id="picture" name="picture" value="{{$photo->picture}}">
            @error('picture')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">@lang('Edit')</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('photos.index')}}">@lang('Back')</a>
    </div>

@endsection

resources/views/photos/index.blade.php
@extends('layouts.app')

@section('content')

    <a href="{{route('photos.create')}}">@lang('Create new photo')</a>

    <div class="row row-cols-1 row-cols-md-5 mt-4">
        @foreach($photos as $photo)
            <div class="card mb-5 mr-3" style="">
                @if($photo->picture == 'no_picture')
                    <a href="{{route('photos.show', ['photo' => $photo])}}">
                        <img src="{{asset('img/no_img.jpg')}}" alt="no_img" class="card-img-top">
                    </a>
                @else
                    <a href="{{route('photos.show', ['photo' => $photo])}}">
                        <img src="{{asset('storage/' . $photo->picture)}}" alt="{{$photo->picture}}" class="card-img-top"
                             style="width: 226px; height: 227px">
                    </a>
                @endif
                    <div class="card-body">
                        <p>{{$photo->title}}</p>
                        <p>@lang('Author'): <a href="{{route('users.show', ['user' => $photo->user])}}">{{$photo->user->name}}</a></p>
                    </div>

            </div>
        @endforeach
    </div>

    <div class="row p-5">
        <div class="col-12">
            {{ $photos->links() }}
        </div>
    </div>

@endsection

resources/views/photos/show.blade.php
@extends('layouts.app')

@section('content')

    <h2>@lang('Author'): {{$photo->user->name}}</h2>

    @if($photo->picture == 'no_picture')
        <img src="{{asset('img/no_img.jpg')}}" alt="no_img">
    @else
        <img src="{{asset('storage/' . $photo->picture)}}" alt="{{$photo->picture}}">
    @endif

    <div>
        @can('update', $photo)
            <a href="{{route('photos.edit', ['photo' => $photo])}}">@lang('Edit')</a>
        @endcan
        @can('delete', $photo)
            <form method="post" action="{{route('photos.destroy', ['photo' => $photo])}}">
                @method('delete')
                @csrf
                <button type="submit" class="btn btn-outline-danger btn-sm">@lang('Remove')</button>
            </form>
        @endcan
    </div>

    <p>@lang('Average score'): {{$average_score}}</p>

    <div>
        <button class="show-comments-btn btn btn-info mt-4" type="button" data-toggle="collapse"
                data-target="#comments-block">@lang('Comments'): <span class="comments-number">{{$comments_count}}</span></button>
        <div id="comments-block" class=" collapse multi-collapse mt-5">
            @foreach($photo->comments as $comment)
                    <div class="card mb-3 w-50">
                        <h5 class="card-header">{{$comment->user->name}}, @lang('Score'): {{$comment->rating}}</h5>
                        <div class="card-body">
                            <p class="card-text">{{$comment->body}}</p>
                            <p class="card-text text-right"><small class="text-muted">{{$comment->created_at->diffForHumans()}}</small></p>
                            <div>
                                @can('update', $comment)
                                    <hr>
                                    <p><a href="{{route('comments.edit', ['comment' => $comment])}}">@lang('Edit comment')</a></p>
                                @endcan
                                @can('delete', $comment)
                                    <form class="mt-3" method="post" action="{{route('comments.destroy', ['comment' => $comment])}}">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-outline-danger btn-sm">@lang('Remove')</button>
                                    </form>
                                @endcan
                            </div>
                        </div>
                    </div>
            @endforeach
        </div>
    </div>

        <form method="post" action="{{route('comments.store')}}" class="w-25 mt-5 mb-5">
            @csrf
            <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">

            <div class="form-group">
                <label for="body">@lang('Comment'):</label>
                <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
                @error('body')
                <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="rating">@lang('Rating')</label>
                <select class="form-control @error('body') is-invalid @enderror" id="rating" name="rating">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                @error('rating')
                <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>
            <button type="submit" class="btn btn-success">@lang('Add comment')</button>
        </form>

    <div class="mt-3 mb-3">
        <a href="{{route('photos.index')}}">@lang('Back')</a>
    </div>

@endsection