routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'language'], function () {
    Auth::routes();
    Route::get('/', 'PhotosController@index')->name('home');
    Route::resource('photos', 'PhotosController');
    Route::resource('users', 'UsersController')->only(['show']);
    Route::resource('comments', 'CommentsController')->except(['index', 'show', 'create']);
});

Route::get('language/{local}', 'LanguageSwitcherController@switcher')->name('language.switcher')
    ->where('local', 'en|ru');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Orchid\Attachment\Attachable;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;

class Comment extends Model
{
    use AsSource, Attachable, Filterable;

    protected $fillable = [
        'user_id',
        'photo_id',
        'body',
        'rating'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\CommentRequest;

class CommentsController extends Controller
{
    /**
     * CommentsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param CommentRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CommentRequest $request)
    {
        $comment = new Comment($request->all());
        $comment->user_id = $request->user()->id;
        $comment->photo_id = $request->input('photo_id');
        $comment->save();
        $photo = $request->input('photo_id');
        return redirect(route('photos.show', compact('photo')))->with('status', 'You have success create comment');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $comment = Comment::findOrFail($id);
        return view('comments.edit', compact('comment'));
    }

    /**
     * @param CommentRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(CommentRequest $request, $id)
    {
        $photo = $request->input('photo_id');
        $comment = Comment::findOrFail($id);
        $this->authorize('update', $comment);
        $comment->update($request->all());
        return redirect(route('photos.show', compact('photo')))->with('status', 'You have success edit comment');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $comment = Comment::findOrFail($id);
        $this->authorize('delete', $comment);
        $photo = $comment->photo->id;
        $comment->delete();
        return redirect(route('photos.show', compact('photo')))->with('status', 'You have success remove comment');
    }
}

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')

    <h2>@lang('Edit Comment')</h2>

    <form method="post" action="{{route('comments.update', ['comment' => $comment])}}" class="w-25 mt-5 mb-5">
        @csrf
        @method('put')
        <input type="hidden" id="photo_id" name="photo_id" value="{{$comment->photo->id}}">

        <div class="form-group">
            <label for="body">@lang('Comment'):</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3">{{$comment->body}}</textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="rating">@lang('Rating')</label>
            <select class="form-control @error('body') is-invalid @enderror" id="rating" name="rating">
                <option @if($comment->rating === '1') selected @endif>1</option>
                <option @if($comment->rating === '2') selected @endif>2</option>
                <option @if($comment->rating === '3') selected @endif>3</option>
                <option @if($comment->rating === '4') selected @endif>4</option>
                <option @if($comment->rating === '5') selected @endif>5</option>
            </select>
            @error('rating')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>
        <button type="submit" class="btn btn-success">@lang('Edit comment')</button>
    </form>

    <div class="mt-3 mb-5">
        <a href="{{route('photos.show', ['photo' => $comment->photo])}}">@lang('Back')</a>
    </div>

@endsection